name: Presubmit tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Compute file changes
        run: |
          echo ${{ github.sha }}
          git status --oneline --all
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          git diff-tree --diff-filter=AM --no-commit-id --name-only -r ${{ github.sha }}

      - name: Install & build dependencies
        run: |
          go get -u golang.org/x/lint/golint
          pip install pylint

      - name: Tests OK
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Testes completados com sucesso!"
          check_for_duplicate_msg: false
        if: ${{ success() }}

      - name: Tests Failed
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Pull-Request com erro! Clique no link [Checks] acima para maiores detalhes."
          check_for_duplicate_msg: false
        if: ${{ failure() }}
